// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/labstack/echo/v4"
	"github.com/taskalataminfo2026/taska-auth-me-go/cmd/api/app/providers"
)

// Injectors from app.go:

func Start() (*echo.Echo, error) {

	echoEcho := providers.ProviderRouter()
	return echoEcho, nil
}
